'use strict';
const STORAGE_KEY='hah_visit_allocation_v1';
const PURPOSES=['IV antibiotics','Labs','ECG','Bladder scan','Nebuliser','Assess wound','PICC dressing change','Neutron change'];
const SHIFT_RULES={
  DAY:{label:'Day 08:00–17:00',firstNormal:'09:00',firstMonWed:'09:30',shiftEnd:'17:00',visitEnd:'16:00',breakLabel:'Lunch',breakMinutes:60,breakEarliest:'11:15',breakLatestStart:'12:15',maxVisits:4},
  PM12:{label:'PM 12:00–21:00',firstNormal:'13:00',firstMonWed:'13:00',shiftEnd:'21:00',visitEnd:'20:15',breakLabel:'Dinner',breakMinutes:90,breakEarliest:'16:45',breakLatestStart:'18:30',maxVisits:4},
  PM13:{label:'PM 13:00–22:00',firstNormal:'14:00',firstMonWed:'14:00',shiftEnd:'22:00',visitEnd:'21:15',breakLabel:'Dinner',breakMinutes:90,breakEarliest:'17:45',breakLatestStart:'19:30',maxVisits:4}
};
const defaultState=()=>({date:nextDateISO(),visits:[],nurses:[newNurse('Nurse 1')],schedule:[],confirmed:false,settings:{jmcPostal:'',nuhPostal:'119074',arrivalBuffer:10,shortThreshold:30},oneMapAvailable:null});
let state=loadState();
let toastTimer;

function nextDateISO(){const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)}
function uid(prefix='id'){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`}
function newNurse(name=''){return{id:uid('n'),name,shift:'DAY',startLocation:'NUH',endLocation:'NUH',notes:''}}
function newVisit(data={}){return{id:uid('v'),bed:'',initials:'',postal:'',type:'Fixed',purposes:[],otherPurpose:'',duration:45,timing:'Flexible',exactTime:'',windowStart:'',windowEnd:'',notes:'',assignedNurseId:'',status:'Active',struckOffAt:null,address:'',lat:null,lng:null,region:'Other',...data}}
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));return x?{...defaultState(),...x,settings:{...defaultState().settings,...x.settings}}:defaultState()}catch{return defaultState()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function mins(t){if(!t)return 0;const[a,b]=t.split(':').map(Number);return a*60+b}
function hhmm(m){m=Math.round(m);return `${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function visitLabel(v){return `${v.bed||'No bed'}${v.initials?` (${v.initials})`:''}`}
function isWestPostal(p){const n=Number(String(p).slice(0,2));return [12,13,14,15,16,21,22,23,24,25,26,27,28,59,60,61,62,63,64,65,66,67,68,69,70,71].includes(n)}
function activeVisits(){return state.visits.filter(v=>v.status!=='Struck off'&&v.type!=='Cancelled')}
function isReady(v){return /^[A-Z]\d+$/.test(v.bed)&&/^[A-Z]{1,5}$/.test(v.initials)&&/^\d{6}$/.test(v.postal)&&v.duration>=15&&(v.purposes.length>0||v.otherPurpose.trim())&&((v.timing!=='Exact'||v.exactTime)&&(v.timing!=='Window'||(v.windowStart&&v.windowEnd)))}
function showToast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function setView(name){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));document.querySelectorAll('#workflowNav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));renderAll()}

function parseBulk(text){const rows=[];const errors=[];text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach((line,i)=>{
  let parts=line.includes('\t')?line.split('\t'):line.includes(',')?line.split(','):line.split(/\s+/);
  parts=parts.map(x=>x.trim()).filter(Boolean);
  let bed='',initials='',postal='';
  if(parts.length===1&&/^\d{6}$/.test(parts[0])) postal=parts[0];
  else if(parts.length>=3){bed=parts[0].replace(/[-\s]/g,'').toUpperCase();initials=parts[1].replace(/[^A-Za-z]/g,'').toUpperCase();postal=(parts.find(x=>/^\d{6}$/.test(x))||parts[2]).replace(/\D/g,'').slice(0,6)}
  else {errors.push(`Line ${i+1}: could not separate Bed, Initials and Postal Code.`);return}
  if(bed&&!/^[A-Z]\d+$/.test(bed))errors.push(`Line ${i+1}: bed must be letter-number, e.g. A12.`);
  if(postal&&!/^\d{6}$/.test(postal))errors.push(`Line ${i+1}: postal code must contain 6 digits.`);
  rows.push(newVisit({bed,initials,postal,region:isWestPostal(postal)?'West':'Other'}));
 });return{rows,errors}}

function renderAll(){document.querySelector('#allocationDate').value=state.date;renderVisits();renderPreparation();renderNurses();renderBoard();renderFinalise();renderNurseSelects();}
function renderVisits(){const count=state.visits.length;document.querySelector('#visitCountPill').textContent=`${count} visit${count===1?'':'s'}`;
 const wrap=document.querySelector('#visitsTableWrap');if(!count){wrap.innerHTML='<div class="card muted">No visits imported yet.</div>';return}
 wrap.innerHTML=`<table class="data-table"><thead><tr><th>Bed</th><th>Initials</th><th>Postal code</th><th>Region</th><th>Preparation</th><th></th></tr></thead><tbody>${state.visits.map(v=>`<tr class="${v.region==='West'?'region-west':'region-other'}"><td><input data-field="bed" data-id="${v.id}" value="${escapeHtml(v.bed)}" aria-label="Bed"></td><td><input data-field="initials" data-id="${v.id}" value="${escapeHtml(v.initials)}" aria-label="Initials"></td><td><input data-field="postal" data-id="${v.id}" value="${escapeHtml(v.postal)}" inputmode="numeric" maxlength="6" aria-label="Postal code"></td><td>${v.region==='West'?'West':'Other'}</td><td>${isReady(v)?'<span class="status-ready">Ready</span>':'<span class="status-incomplete">Incomplete</span>'}</td><td><button class="mini-button edit-visit" data-id="${v.id}">Edit</button> <button class="mini-button delete-visit" data-id="${v.id}">Delete</button></td></tr>`).join('')}</tbody></table>`;
 wrap.querySelectorAll('input[data-field]').forEach(el=>el.addEventListener('change',e=>{const v=state.visits.find(x=>x.id===e.target.dataset.id);let val=e.target.value.trim();if(e.target.dataset.field==='bed')val=val.replace(/[-\s]/g,'').toUpperCase();if(e.target.dataset.field==='initials')val=val.replace(/[^A-Za-z]/g,'').toUpperCase();if(e.target.dataset.field==='postal'){val=val.replace(/\D/g,'').slice(0,6);v.region=isWestPostal(val)?'West':'Other';v.address='';v.lat=null;v.lng=null}v[e.target.dataset.field]=val;clearSchedule();saveState();renderAll()}));
 wrap.querySelectorAll('.edit-visit').forEach(b=>b.addEventListener('click',()=>openVisitDialog(b.dataset.id)));
 wrap.querySelectorAll('.delete-visit').forEach(b=>b.addEventListener('click',()=>{if(confirm('Delete this visit?')){state.visits=state.visits.filter(x=>x.id!==b.dataset.id);clearSchedule();saveState();renderAll()}}));}
function renderPreparation(){const ready=state.visits.filter(isReady).length;document.querySelector('#readyCountPill').textContent=`${ready} / ${state.visits.length} ready`;const el=document.querySelector('#preparationList');if(!state.visits.length){el.innerHTML='<div class="card muted">Import visits first.</div>';return}el.innerHTML=state.visits.map(v=>`<div class="card prep-card ${v.region==='West'?'region-west':'region-other'}"><div><div class="visit-id">${escapeHtml(visitLabel(v))}</div><div class="muted">${escapeHtml(v.postal)}${v.address?` · ${escapeHtml(v.address)}`:''}</div></div><div><div class="task-tags">${[...v.purposes,v.otherPurpose].filter(Boolean).map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join('')||'<span class="muted">No task selected</span>'}</div><div class="muted">${v.duration} min · ${escapeHtml(v.timing)} · ${escapeHtml(v.type)}</div></div><div><div class="${isReady(v)?'status-ready':'status-incomplete'}">${isReady(v)?'Ready':'Incomplete'}</div><button class="mini-button prep-edit" data-id="${v.id}">Prepare</button></div></div>`).join('');el.querySelectorAll('.prep-edit').forEach(b=>b.addEventListener('click',()=>openVisitDialog(b.dataset.id)))}
function renderNurses(){const el=document.querySelector('#nurseList');el.innerHTML=state.nurses.map((n,i)=>`<div class="nurse-card"><div class="nurse-card-head"><strong>${escapeHtml(n.name||`Nurse ${i+1}`)}</strong><button class="mini-button delete-nurse" data-id="${n.id}">Delete</button></div><div class="form-grid"><label>Name<input data-nurse-field="name" data-id="${n.id}" value="${escapeHtml(n.name)}"></label><label>Shift<select data-nurse-field="shift" data-id="${n.id}">${Object.entries(SHIFT_RULES).map(([k,r])=>`<option value="${k}" ${n.shift===k?'selected':''}>${r.label}</option>`).join('')}</select></label><label>Start location<select data-nurse-field="startLocation" data-id="${n.id}">${['JMC','NUH','Home'].map(x=>`<option ${n.startLocation===x?'selected':''}>${x}</option>`).join('')}</select></label><label>End location<select data-nurse-field="endLocation" data-id="${n.id}">${['JMC','NUH','Home'].map(x=>`<option ${n.endLocation===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label>Operational notes<textarea data-nurse-field="notes" data-id="${n.id}" rows="2">${escapeHtml(n.notes)}</textarea></label></div>`).join('');el.querySelectorAll('[data-nurse-field]').forEach(x=>x.addEventListener('change',e=>{const n=state.nurses.find(y=>y.id===e.target.dataset.id);n[e.target.dataset.nurseField]=e.target.value;clearSchedule();saveState();renderAll()}));el.querySelectorAll('.delete-nurse').forEach(b=>b.addEventListener('click',()=>{if(state.nurses.length===1)return showToast('At least one nurse is required.');if(confirm('Delete this nurse?')){state.nurses=state.nurses.filter(x=>x.id!==b.dataset.id);state.visits.forEach(v=>{if(v.assignedNurseId===b.dataset.id)v.assignedNurseId=''});clearSchedule();saveState();renderAll()}}))}
function renderNurseSelects(){const opts=`<option value="">Auto</option>${state.nurses.map(n=>`<option value="${n.id}">${escapeHtml(n.name)}</option>`).join('')}`;document.querySelector('#dialogAssignedNurse').innerHTML=opts;const f=document.querySelector('#nurseFilter');const cur=f.value;f.innerHTML=`<option value="all">All nurses</option>${state.nurses.map(n=>`<option value="${n.id}">${escapeHtml(n.name)}</option>`).join('')}`;if([...f.options].some(o=>o.value===cur))f.value=cur}

function renderBoard(){const filter=document.querySelector('#nurseFilter').value||'all';const schedule=filter==='all'?state.schedule:state.schedule.filter(s=>s.nurseId===filter);const active=activeVisits();const allocatedIds=new Set(state.schedule.flatMap(s=>s.items.filter(x=>x.kind==='visit').map(x=>x.visitId)));const unallocated=active.filter(v=>!allocatedIds.has(v.id));document.querySelector('#allocationSummary').innerHTML=[['Visits',active.length],['Allocated',allocatedIds.size],['Nurses',state.nurses.length],['Unallocated',unallocated.length]].map(([k,v])=>`<div class="summary-card"><span class="muted">${k}</span><strong>${v}</strong></div>`).join('');const grid=document.querySelector('#boardGrid');if(!state.schedule.length){grid.innerHTML='<div class="card muted">Complete visit preparation and nurse roster, then select Allocate Visits.</div>';document.querySelector('#unallocatedPanel').innerHTML='';return}grid.innerHTML=schedule.map(s=>{const n=state.nurses.find(x=>x.id===s.nurseId);return`<article class="board-card"><header class="board-card-header"><div><strong>${escapeHtml(n?.name||'Nurse')}</strong><div class="muted">${SHIFT_RULES[n?.shift]?.label||''} · ${n?.startLocation} → ${n?.endLocation}</div></div><button class="mini-button add-adhoc" data-nurse="${s.nurseId}">+ Ad hoc</button></header><div class="timeline">${s.items.map(item=>renderTimelineItem(item,s.nurseId)).join('')}<div class="muted">${escapeHtml(s.availabilityText||'')}</div></div></article>`}).join('');grid.querySelectorAll('.add-adhoc').forEach(b=>b.addEventListener('click',()=>{const v=newVisit({type:'Ad hoc',assignedNurseId:b.dataset.nurse,duration:30});state.visits.push(v);saveState();openVisitDialog(v.id)}));grid.querySelectorAll('.strike').forEach(b=>b.addEventListener('click',()=>strikeVisit(b.dataset.id,false)));grid.querySelectorAll('.replace').forEach(b=>b.addEventListener('click',()=>strikeVisit(b.dataset.id,true)));grid.querySelectorAll('.move-select').forEach(x=>x.addEventListener('change',e=>{const v=state.visits.find(y=>y.id===e.target.dataset.id);v.assignedNurseId=e.target.value;clearSchedule();saveState();renderAll();showToast('Nurse changed. Select Allocate Visits to recalculate.')}));document.querySelector('#unallocatedPanel').innerHTML=unallocated.length?`<h3>Unallocated visits</h3><div class="unallocated-list">${unallocated.map(v=>`<button class="unallocated-chip edit-visit" data-id="${v.id}">${escapeHtml(visitLabel(v))}</button>`).join('')}</div>`:'';document.querySelectorAll('#unallocatedPanel .edit-visit').forEach(b=>b.addEventListener('click',()=>openVisitDialog(b.dataset.id)))}
function renderTimelineItem(item,nurseId){if(item.kind==='travel')return`<div class="timeline-travel">🚗 ${item.minutes} min · ${item.km!=null?`${item.km.toFixed(1)} km`:'estimated travel'}</div>`;if(item.kind==='break')return`<div class="timeline-item timeline-break"><strong>${hhmm(item.start)}–${hhmm(item.end)} ${item.label}</strong></div>`;if(item.kind==='base')return`<div class="timeline-item"><strong>${hhmm(item.time)} ${escapeHtml(item.label)}</strong></div>`;const v=state.visits.find(x=>x.id===item.visitId);if(!v)return'';return`<div class="timeline-item ${v.status==='Struck off'?'cancelled':''} ${v.region==='West'?'region-west':'region-other'}"><strong>${hhmm(item.start)}–${hhmm(item.end)} ${escapeHtml(visitLabel(v))}</strong><div class="muted">${escapeHtml(v.postal)} · ${v.duration} min · ${escapeHtml([...v.purposes,v.otherPurpose].filter(Boolean).join(', '))}</div><div class="timeline-actions"><select class="move-select" data-id="${v.id}">${state.nurses.map(n=>`<option value="${n.id}" ${n.id===nurseId?'selected':''}>${escapeHtml(n.name)}</option>`).join('')}</select><button class="mini-button strike" data-id="${v.id}">Strike off</button><button class="mini-button replace" data-id="${v.id}">Strike off & replace</button></div></div>`}
function renderFinalise(){const active=activeVisits(),allocated=new Set(state.schedule.flatMap(s=>s.items.filter(i=>i.kind==='visit').map(i=>i.visitId)));const warnings=[];if(!state.schedule.length)warnings.push('No allocation has been created.');if(active.some(v=>!allocated.has(v.id)))warnings.push(`${active.filter(v=>!allocated.has(v.id)).length} visit(s) remain unallocated.`);state.schedule.forEach(s=>(s.warnings||[]).forEach(w=>warnings.push(`${state.nurses.find(n=>n.id===s.nurseId)?.name}: ${w}`)));const el=document.querySelector('#finalChecks');el.innerHTML=`${state.confirmed?'<div class="locked-banner">Allocation confirmed and locked.</div>':''}<h3>Final checks</h3>${warnings.length?`<ul class="warning-list bad">${warnings.map(w=>`<li>${escapeHtml(w)}</li>`).join('')}</ul>`:'<p class="good">✓ Allocation is ready for review and sharing.</p>'}<p class="muted">Visits: ${active.length} · Nurses: ${state.nurses.length} · Status: ${state.confirmed?'Finalised':'Draft'}</p>`}

function openVisitDialog(id){const v=state.visits.find(x=>x.id===id);if(!v)return;document.querySelector('#dialogVisitId').value=v.id;document.querySelector('#visitDialogTitle').textContent=`Prepare ${visitLabel(v)}`;for(const [id2,val] of [['dialogBed',v.bed],['dialogInitials',v.initials],['dialogPostal',v.postal],['dialogType',v.type],['dialogDuration',v.duration],['dialogTiming',v.timing],['dialogExactTime',v.exactTime],['dialogWindowStart',v.windowStart],['dialogWindowEnd',v.windowEnd],['dialogAssignedNurse',v.assignedNurseId],['dialogOtherPurpose',v.otherPurpose],['dialogNotes',v.notes]])document.querySelector(`#${id2}`).value=val;document.querySelector('#dialogPurposes').innerHTML=PURPOSES.map(p=>`<label><input type="checkbox" value="${p}" ${v.purposes.includes(p)?'checked':''}> ${p}</label>`).join('');toggleTimingFields();document.querySelector('#visitDialog').showModal()}
function toggleTimingFields(){const t=document.querySelector('#dialogTiming').value;document.querySelector('#exactTimeLabel').style.display=t==='Exact'?'grid':'none';document.querySelector('#windowStartLabel').style.display=t==='Window'?'grid':'none';document.querySelector('#windowEndLabel').style.display=t==='Window'?'grid':'none'}
function saveVisitDialog(){const v=state.visits.find(x=>x.id===document.querySelector('#dialogVisitId').value);if(!v)return;v.bed=document.querySelector('#dialogBed').value.replace(/[-\s]/g,'').toUpperCase();v.initials=document.querySelector('#dialogInitials').value.replace(/[^A-Za-z]/g,'').toUpperCase();const oldPostal=v.postal;v.postal=document.querySelector('#dialogPostal').value.replace(/\D/g,'').slice(0,6);v.type=document.querySelector('#dialogType').value;v.duration=Math.max(15,Number(document.querySelector('#dialogDuration').value)||45);v.timing=document.querySelector('#dialogTiming').value;v.exactTime=document.querySelector('#dialogExactTime').value;v.windowStart=document.querySelector('#dialogWindowStart').value;v.windowEnd=document.querySelector('#dialogWindowEnd').value;v.assignedNurseId=document.querySelector('#dialogAssignedNurse').value;v.purposes=[...document.querySelectorAll('#dialogPurposes input:checked')].map(x=>x.value);v.otherPurpose=document.querySelector('#dialogOtherPurpose').value.trim();v.notes=document.querySelector('#dialogNotes').value.trim();v.region=isWestPostal(v.postal)?'West':'Other';if(oldPostal!==v.postal){v.address='';v.lat=null;v.lng=null}if(v.type==='Cancelled'){v.status='Struck off';v.struckOffAt=v.struckOffAt||new Date().toISOString()}else if(v.status==='Struck off'&&!v.struckOffAt){v.status='Active'}clearSchedule();saveState();document.querySelector('#visitDialog').close();renderAll();showToast('Visit saved')}
function strikeVisit(id,replace){const v=state.visits.find(x=>x.id===id);if(!v)return;if(!confirm(replace?'Strike off this visit and create a replacement?':'Strike off this visit?'))return;v.type='Cancelled';v.status='Struck off';v.struckOffAt=new Date().toISOString();if(replace){const nv=newVisit({type:'Ad hoc',assignedNurseId:v.assignedNurseId,duration:v.duration,timing:v.timing,exactTime:v.exactTime,windowStart:v.windowStart,windowEnd:v.windowEnd,notes:`Replacement for ${visitLabel(v)}`});state.visits.push(nv);clearSchedule();saveState();renderAll();openVisitDialog(nv.id)}else{clearSchedule();saveState();renderAll()}}
function clearSchedule(){state.schedule=[];state.confirmed=false}

async function api(path,options){const r=await fetch(path,options);const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`Request failed (${r.status})`);return body}
async function checkRouting(){try{const x=await api('/api/health');state.oneMapAvailable=!!x.configured;return state.oneMapAvailable}catch{state.oneMapAvailable=false;return false}}
async function geocodeVisits(visits){for(let i=0;i<visits.length;i++){const v=visits[i];if(v.lat&&v.lng)continue;document.querySelector('#routingStatus').textContent=`Validating postal codes with OneMap (${i+1}/${visits.length})…`;const data=await api(`/api/search?postal=${encodeURIComponent(v.postal)}`);v.address=data.address||'';v.lat=Number(data.lat);v.lng=Number(data.lng)}}
async function geocodeBase(location){if(location==='Home')return null;const postal=location==='JMC'?state.settings.jmcPostal:state.settings.nuhPostal;if(!/^\d{6}$/.test(postal))return null;const data=await api(`/api/search?postal=${postal}`);return{lat:Number(data.lat),lng:Number(data.lng),address:data.address,postal}}
function haversine(a,b){if(!a||!b)return 999;const R=6371,toR=x=>x*Math.PI/180,dLat=toR(b.lat-a.lat),dLng=toR(b.lng-a.lng);const s=Math.sin(dLat/2)**2+Math.cos(toR(a.lat))*Math.cos(toR(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
async function route(a,b){if(!a||!b)return{minutes:0,km:null};try{return await api(`/api/route?start=${a.lat},${a.lng}&end=${b.lat},${b.lng}`)}catch{return{minutes:Math.max(8,Math.round(haversine(a,b)*3.2)),km:haversine(a,b),estimated:true}}}
function orderedVisitsForNurse(visits,startPoint){const exact=[...visits.filter(v=>v.timing==='Exact')].sort((a,b)=>mins(a.exactTime)-mins(b.exactTime));let flexible=visits.filter(v=>v.timing!=='Exact');const ordered=[...exact];let current=startPoint||flexible[0];while(flexible.length){flexible.sort((a,b)=>haversine(current,a)-haversine(current,b));const next=flexible.shift();ordered.push(next);current=next}return ordered}
function chooseNurse(v,buckets,startPoints){if(v.assignedNurseId&&buckets[v.assignedNurseId])return v.assignedNurseId;const candidates=state.nurses.filter(n=>{const b=buckets[n.id];const limit=SHIFT_RULES[n.shift].maxVisits;const canFifth=b.length<5&&(v.duration<=state.settings.shortThreshold||b.some(x=>x.duration<=state.settings.shortThreshold));return b.length<limit||(b.length===limit&&canFifth)});if(!candidates.length)return'';candidates.sort((a,b)=>{const al=buckets[a.id].at(-1)||startPoints[a.id],bl=buckets[b.id].at(-1)||startPoints[b.id];return (buckets[a.id].length-buckets[b.id].length)*10+haversine(al,v)-haversine(bl,v)});return candidates[0].id}
async function buildSchedule(){if(state.confirmed)return showToast('Unlock the finalised allocation first.');const visits=activeVisits();if(!visits.length)return showToast('Add at least one active visit.');if(!state.nurses.length)return showToast('Add at least one nurse.');const incomplete=visits.filter(v=>!isReady(v));if(incomplete.length&&!confirm(`${incomplete.length} visit(s) are incomplete. Continue anyway?`))return;
 const routing=await checkRouting();document.querySelector('#routingStatus').className=`feedback ${routing?'success':''}`;document.querySelector('#routingStatus').textContent=routing?'OneMap connected. Validating visits and calculating driving routes…':'OneMap backend is not configured. Allocation will use postal-region approximations until Vercel is configured.';
 if(routing){try{await geocodeVisits(visits)}catch(e){document.querySelector('#routingStatus').className='feedback error';document.querySelector('#routingStatus').textContent=`OneMap validation stopped: ${e.message}`;return}}
 const startPoints={};if(routing){for(const n of state.nurses){try{startPoints[n.id]=await geocodeBase(n.startLocation)}catch{startPoints[n.id]=null}}}
 const buckets=Object.fromEntries(state.nurses.map(n=>[n.id,[]]));const priority=[...visits].sort((a,b)=>{const rank=x=>x.timing==='Exact'?0:x.timing==='Window'?1:x.timing==='AM'?2:x.timing==='PM'?3:4;return rank(a)-rank(b)});const unallocated=[];for(const v of priority){const id=chooseNurse(v,buckets,startPoints);if(id){buckets[id].push(v);v.assignedNurseId=id}else unallocated.push(v.id)}
 const dow=new Date(`${state.date}T12:00:00`).getDay();const monWed=dow===1||dow===3;const schedules=[];for(const n of state.nurses){const rule=SHIFT_RULES[n.shift];const ordered=orderedVisitsForNurse(buckets[n.id],startPoints[n.id]);let t=mins(monWed?rule.firstMonWed:rule.firstNormal);let current=startPoints[n.id];let breakTaken=false;const items=[];const warnings=[];if(n.startLocation!=='Home')items.push({kind:'base',time:Math.max(0,t-30),label:`Start from ${n.startLocation}`});for(let i=0;i<ordered.length;i++){const v=ordered[i];let travel={minutes:0,km:null};if(current&&v.lat)travel=await route(current,v);if(travel.minutes){items.push({kind:'travel',minutes:travel.minutes,km:travel.km});t+=travel.minutes+Number(state.settings.arrivalBuffer||0)}
   const breakEarliest=mins(rule.breakEarliest),breakLatest=mins(rule.breakLatestStart);if(!breakTaken&&t>=breakEarliest&&t<=breakLatest&&t+v.duration>breakLatest+rule.breakMinutes){items.push({kind:'break',start:t,end:t+rule.breakMinutes,label:rule.breakLabel});t+=rule.breakMinutes;breakTaken=true}
   if(v.timing==='Exact'&&mins(v.exactTime)>t)t=mins(v.exactTime);if(v.timing==='Window'&&mins(v.windowStart)>t)t=mins(v.windowStart);if(v.timing==='AM'&&t>=12*60)warnings.push(`${visitLabel(v)} is marked AM but scheduled after noon.`);if(v.timing==='PM'&&t<13*60)t=13*60;
   const start=t,end=t+v.duration;if(v.timing==='Exact'&&Math.abs(start-mins(v.exactTime))>5)warnings.push(`${visitLabel(v)} misses exact time ${v.exactTime}.`);if(v.timing==='Window'&&end>mins(v.windowEnd))warnings.push(`${visitLabel(v)} exceeds its time window.`);items.push({kind:'visit',visitId:v.id,start,end});t=end;current=v.lat?v:current}
  if(!breakTaken&&ordered.length){const bs=Math.max(mins(rule.breakEarliest),Math.min(t,mins(rule.breakLatestStart)));items.push({kind:'break',start:bs,end:bs+rule.breakMinutes,label:rule.breakLabel});breakTaken=true;if(bs<t)warnings.push(`${rule.breakLabel} could not be placed naturally between visits; review sequence.`)}
  if(t>mins(rule.visitEnd))warnings.push(`Last visit ends at ${hhmm(t)}, after preferred ${rule.visitEnd}.`);if(ordered.length>4&&!ordered.some(v=>v.duration<=state.settings.shortThreshold))warnings.push('Five visits assigned without a qualifying short visit.');if(n.endLocation!=='Home'){let endBase=null;if(routing)try{endBase=await geocodeBase(n.endLocation)}catch{};if(current&&endBase){const r=await route(current,endBase);items.push({kind:'travel',minutes:r.minutes,km:r.km});t+=r.minutes;items.push({kind:'base',time:t,label:`Return to ${n.endLocation}`})}else items.push({kind:'base',time:t,label:`End at ${n.endLocation}`})}
  schedules.push({nurseId:n.id,items,warnings,availabilityText:t<mins(rule.visitEnd)?`Available from ${hhmm(t)} to ${rule.visitEnd}`:`Estimated finish ${hhmm(t)}`})}
 state.schedule=schedules;state.confirmed=false;saveState();document.querySelector('#routingStatus').textContent=routing?'Allocation completed with OneMap travel calculations.':'Allocation completed without live routing. Configure Vercel before real-world testing.';renderAll();showToast('Visits allocated')}

function resetAllocation(){if(!confirm('Reset all nurse assignments and the generated timetable? Visit and nurse details will be kept.'))return;state.visits.forEach(v=>{if(v.status!=='Struck off')v.assignedNurseId=''});state.schedule=[];state.confirmed=false;saveState();renderAll();showToast('Allocation reset')}
function exportCsv(){const rows=[['Nurse','Shift','Start','End','Time','Bed','Initials','Postal','Purpose','Duration','Type']];state.schedule.forEach(s=>{const n=state.nurses.find(x=>x.id===s.nurseId);s.items.filter(i=>i.kind==='visit').forEach(i=>{const v=state.visits.find(x=>x.id===i.visitId);rows.push([n.name,SHIFT_RULES[n.shift].label,n.startLocation,n.endLocation,`${hhmm(i.start)}-${hhmm(i.end)}`,v.bed,v.initials,v.postal,[...v.purposes,v.otherPurpose].filter(Boolean).join('; '),v.duration,v.type])})});const csv=rows.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`HaH-Visit-Allocation-${state.date}.csv`;a.click();URL.revokeObjectURL(a.href)}

// events
document.querySelectorAll('#workflowNav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
document.querySelector('#allocationDate').addEventListener('change',e=>{state.date=e.target.value;clearSchedule();saveState();renderAll()});
document.querySelector('#importVisitsBtn').addEventListener('click',()=>{const {rows,errors}=parseBulk(document.querySelector('#bulkInput').value);state.visits.push(...rows);clearSchedule();saveState();document.querySelector('#visitImportFeedback').className=`feedback ${errors.length?'error':'success'}`;document.querySelector('#visitImportFeedback').textContent=`Imported ${rows.length} visit(s).${errors.length?` ${errors.join(' ')}`:''}`;renderAll()});
document.querySelector('#addBlankVisitBtn').addEventListener('click',()=>{const v=newVisit();state.visits.push(v);saveState();renderAll();openVisitDialog(v.id)});document.querySelector('#clearBulkBtn').addEventListener('click',()=>document.querySelector('#bulkInput').value='');
document.querySelector('#addNurseBtn').addEventListener('click',()=>{state.nurses.push(newNurse(`Nurse ${state.nurses.length+1}`));clearSchedule();saveState();renderAll()});
document.querySelector('#dialogTiming').addEventListener('change',toggleTimingFields);document.querySelector('#saveVisitDialogBtn').addEventListener('click',e=>{e.preventDefault();saveVisitDialog()});
document.querySelector('#allocateBtn').addEventListener('click',buildSchedule);document.querySelector('#resetAllocationBtn').addEventListener('click',resetAllocation);document.querySelector('#nurseFilter').addEventListener('change',renderBoard);
document.querySelector('#confirmAllocationBtn').addEventListener('click',()=>{if(!state.schedule.length)return showToast('Allocate visits first.');state.confirmed=true;saveState();renderAll();showToast('Allocation finalised')});document.querySelector('#unlockBtn').addEventListener('click',()=>{state.confirmed=false;saveState();renderAll();showToast('Allocation unlocked')});document.querySelector('#printBtn').addEventListener('click',()=>window.print());document.querySelector('#exportCsvBtn').addEventListener('click',exportCsv);
document.querySelector('#settingsBtn').addEventListener('click',()=>{document.querySelector('#jmcPostal').value=state.settings.jmcPostal;document.querySelector('#nuhPostal').value=state.settings.nuhPostal;document.querySelector('#arrivalBuffer').value=state.settings.arrivalBuffer;document.querySelector('#shortThreshold').value=state.settings.shortThreshold;document.querySelector('#settingsDialog').showModal()});document.querySelector('#saveSettingsBtn').addEventListener('click',e=>{e.preventDefault();state.settings.jmcPostal=document.querySelector('#jmcPostal').value.replace(/\D/g,'').slice(0,6);state.settings.nuhPostal=document.querySelector('#nuhPostal').value.replace(/\D/g,'').slice(0,6);state.settings.arrivalBuffer=Number(document.querySelector('#arrivalBuffer').value)||0;state.settings.shortThreshold=Number(document.querySelector('#shortThreshold').value)||30;clearSchedule();saveState();document.querySelector('#settingsDialog').close();renderAll();showToast('Settings saved')});
renderAll();
